### ISSUE TITLE
module requires csh to be installed on Ubuntu

### ISSUE THREAD

**Issue by djgreen** [treydock/puppet-lmod#32]
If you don't have csh installed on the Ubuntu computer, puppet fails:

Error: Could not set 'file' on ensure: No such file or directory - A directory component in /etc/csh/login.d/lmod.csh20210916-3656-11yq1pr.lock does not exist or is a dangling symbolic link (file: /etc/puppetlabs/code/environments/ece_production/modules/lmod/manifests/load.pp, line: 49)
Error: Could not set 'file' on ensure: No such file or directory - A directory component in /etc/csh/login.d/lmod.csh20210916-3656-11yq1pr.lock does not exist or is a dangling symbolic link (file: /etc/puppetlabs/code/environments/ece_production/modules/lmod/manifests/load.pp, line: 49)
Wrapped exception:
No such file or directory - A directory component in /etc/csh/login.d/lmod.csh20210916-3656-11yq1pr.lock does not exist or is a dangling symbolic link
Error: /Stage[main]/Lmod::Load/File[lmod-csh-load]/ensure: change from 'absent' to 'file' failed: Could not set 'file' on ensure: No such file or directory - A directory component in /etc/csh/login.d/lmod.csh20210916-3656-11yq1pr.lock does not exist or is a dangling symbolic link (file: /etc/puppetlabs/code/environments/ece_production/modules/lmod/manifests/load.pp, line: 49)

Once you manually install csh, this all works. But really shouldn't require it if we're not using it. 
(technically, this probably applies to both RHEL and Ubuntu)

**Comment by treydock** [comment]
This wouldn't apply to RHEL because there is no such thing as `/etc/csh` , the `lmod.csh` file on RHEL goes directly into `/etc/profile.d` which is present even on minimal containers for RHEL.

For Ubuntu, it sounds like just need to add another runtime package for Lmod. This module already installs `tcsh` for Debian based systems, so likely just need to expand that to include `csh`.  The only way to make this module manage something if csh is present is to add a fact to check if csh is installed but really it's a lot simpler to just install csh like is already done for other shells.

https://github.com/treydock/puppet-lmod/blob/df9c63d1d52a64714a8fe322a9a539061e8e42a1/data/os/Debian.yaml#L9-L17

If you truly don't want csh installed on your systems then I think need a new parameter to turn off adding the `lmod.csh` file.

**Comment by djgreen** [comment]
True, if you're already installing tcsh, might as well just add csh.

**Comment by treydock** [comment]
This will be released in v3.0.1 when the Github Actions complete.
